import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: (
    <>
      <meta property="og:title" content="Frame" />
      <meta property="og:image" content={`${BASE_URL}/question.jpg`} />
      <meta property="fc:frame" content="vNext" />
      <meta property="fc:frame:image" content={`${BASE_URL}/question.jpg`} />
      <meta property="fc:frame:button:1" content="Yes" />
      <meta property="fc:frame:button:2" content="No" />
      <meta property="fc:frame:post_url" content={`${BASE_URL}/api/post`} />
    </>
  ),
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
